a-house-divided:
    - 'A House Divided'
demon-queen-awakens:
    - 'The Demon Queen Awakens'
ferncombe:   
    - 'Ferncombe'
atropos-patreon-battlemaps:
    - 'Patreon Battlemaps by Atropos'
dnd-phandelver-below:
    - 'Phandelver and Below: The Shattered Obelisk'
dnd-tashas-cauldron:
    - "Tasha's Cauldron of Everything"

pf2e-beginner-box:
    - 'Pathfinder: Beginner Box'
pf2e-abomination-vaults:
    - 'Pathfinder: Abomination Vaults'
pf2e-tokens-bestiaries:
    - 'Pathfinder Token Pack: Bestiaries'
pf2e-decks-harrow:
    - 'Pathfinder: Harrow Deck'
pf2e-kingmaker:
    - 'Pathfinder: Kingmaker'
