a-house-divided:
    - 'A House Divided'
demon-queen-awakens:
    - 'The Demon Queen Awakens'

pf2e-beginner-box:
    - 'Pathfinder: Beginner Box'
pf2e-abomination-vaults:
    - 'Pathfinder: Abomination Vaults'
pf2e-tokens-bestiaries:
    - 'Pathfinder Token Pack: Bestiaries'
    
atropos-patreon-battlemaps:
  - 'Atropos' Patreon Battlemaps'
  
kp-tome-of-beasts:
  - 'Tome of Beasts by Kobold Press'
kp-book-of-lairs:
  - 'Book of Lairs by Kobold Press'

apotheosis-sirens:
  - 'The Red Opera by Apotheosis Studios'
apotheosis-red-opera:
  - 'Sirens - Battle of the Bards by Apotheosis Studios'
