a-house-divided:
    - 'A House Divided'
demon-queen-awakens:
    - 'The Demon Queen Awakens'
ferncombe:   
    - 'Ferncombe'
atropos-patreon-battlemaps:
    - 'Patreon Battlemaps by Atropos'
dnd-phandelver-below:
    - 'Phandelver and Below: The Shattered Obelisk'
dnd-tashas-cauldron:
    - "Tasha's Cauldron of Everything"
dnd-players-handbook:
    - "Dungeons & Dragons Player's Handbook"
dnd-dungeon-masters-guide:
    - "Dungeons & Dragons Dungeon Master's Guide"
dnd-monster-manual:
    - "Dungeons & Dragons Monster Manual"

pf2e-beginner-box:
    - 'Pathfinder: Beginner Box'
pf2e-abomination-vaults:
    - 'Pathfinder: Abomination Vaults'
pf2e-tokens-bestiaries:
    - 'Pathfinder Tokens: Bestiaries'
pf2e-tokens-characters:
    - 'Pathfinder Tokens: Characters'
pf2e-decks-harrow:
    - 'Pathfinder: Harrow Deck'
pf2e-kingmaker:
    - 'Pathfinder: Kingmaker'
