name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to report an issue with a piece of premium content that Foundry has ownership over
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: What package are you reporting this for?
      multiple: false
      options:
      - "The Demon Queen Awakens"
      - "A House Divided"
      - "Ferncombe"
      - "Patreon Battlemaps by Atropos"
      - "Pathfinder: Beginner Box"
      - "Pathfinder: Abomination Vaults"
      - "Pathfinder Tokens: Bestiaries"
      - "Pathfinder Tokens: Characters"
      - "Pathfinder: Harrow Deck"
      - "Pathfinder: Kingmaker"
      - "Phandelver and Below: The Shattered Obelisk"
      - "Tasha's Cauldron of Everything"
      - "Dungeons & Dragons Player's Handbook"
      - "Dungeons & Dragons Dungeon Master's Guide"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package?
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
