name: Feature Request
description: Request a new feature
title: "[Feature]: "
labels: ["Feature"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to suggest a new feature for a piece of premium content that Foundry has ownership over
  - type: textarea
    id: feature
    attributes:
      label: What is the feature?
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: What package are you reporting this for?
      multiple: false
      options:
      - "The Demon Queen Awakens"
      - "A House Divided"
      - "Ferncombe"
      - "Patreon Battlemaps by Atropos"
      - "Pathfinder: Beginner Box"
      - "Pathfinder: Abomination Vaults"
      - "Pathfinder: Kingmaker"
      - "Pathfinder: Claws of the Tyrant"
      - "Pathfinder Tokens: Bestiaries"
      - "Pathfinder Tokens: Character Gallery"
      - "Pathfinder Tokens: Myth and Magic"
      - "Pathfinder: Harrow Deck"
      - "Dungeons & Dragons Phandelver and Below: The Shattered Obelisk"
      - "Dungeons & Dragons Tasha's Cauldron of Everything"
      - "Dungeons & Dragons Player's Handbook"
      - "Dungeons & Dragons Dungeon Master's Guide"
      - "Dungeons & Dragons Monster Manual"
      - "Dungeons & Dragons Tomb of Annihilation"
      - "Dungeons & Dragons Heroes of the Borderlands"
      - "Dungeons & Dragons Forgotten Realms: Heroes of Faerûn"
      - "Dungeons & Dragons Forgotten Realms: Adventures in Faerûn"
